import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { C } from '@/lib/theme'

const S = {
  h2: { fontSize: 14, fontWeight: 700, color: C.textPrimary, margin: '28px 0 10px', letterSpacing: '-0.01em' },
  p:  { fontSize: 12, color: C.textSecondary, lineHeight: 1.8, marginBottom: 12 },
  li: { fontSize: 12, color: C.textSecondary, lineHeight: 1.8, marginBottom: 6, marginLeft: 16 },
}

export default function Terms() {
  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '40px 24px', fontFamily: "'Cascadia Code','JetBrains Mono',monospace" }}>
      <Link to="/login" style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: C.textMuted, marginBottom: 32, textDecoration: 'none' }}>
        <ArrowLeft size={12} /> Back to sign in
      </Link>

      <div style={{ fontSize: 22, fontWeight: 700, color: C.textPrimary, letterSpacing: '-0.02em', marginBottom: 6 }}>
        Terms of Service
      </div>
      <div style={{ fontSize: 10, color: C.textMuted, marginBottom: 36 }}>
        Effective date: 1 June 2025 · Last updated: 1 June 2025
      </div>

      <div style={{ borderTop: `1px solid ${C.border}`, paddingTop: 24 }}>

        <h2 style={S.h2}>1. Acceptance of terms</h2>
        <p style={S.p}>By creating an account and using Mercury you agree to these Terms of Service. If you do not agree, do not use the service.</p>

        <h2 style={S.h2}>2. Description of service</h2>
        <p style={S.p}>Mercury is a research-grade automatic speech recognition (ASR) platform providing phoneme diagnostics, acoustic drift detection, TTS remediation, and LoRA fine-tuning capabilities. The service is provided for research and educational purposes.</p>

        <h2 style={S.h2}>3. Eligibility</h2>
        <p style={S.p}>You must be at least 13 years of age to use this service. By using the service you represent that you meet this requirement.</p>

        <h2 style={S.h2}>4. Acceptable use</h2>
        <p style={S.p}>You agree not to:</p>
        <ul>
          <li style={S.li}>Upload audio containing content that is illegal, harmful, or violates the rights of others</li>
          <li style={S.li}>Attempt to reverse-engineer, decompile, or extract the underlying models</li>
          <li style={S.li}>Use the service to process audio of individuals without their consent</li>
          <li style={S.li}>Attempt to circumvent authentication or access controls (except features explicitly provided)</li>
          <li style={S.li}>Use the service for commercial purposes without explicit written permission</li>
          <li style={S.li}>Overload the service with automated requests</li>
        </ul>

        <h2 style={S.h2}>5. Intellectual property</h2>
        <p style={S.p}>The Mercury codebase is open-source and licensed under the terms in the repository. The underlying models (Wav2Vec2, Bark) are subject to their respective licences from Meta AI and Suno AI. Transcription outputs generated by the service are owned by you.</p>

        <h2 style={S.h2}>6. Research use and accuracy</h2>
        <p style={S.p}>Mercury is a research prototype. ASR output, confidence scores, phoneme diagnostics, and all other outputs are provided on an "as-is" basis. We make no warranties about accuracy. Do not use this service for medical, legal, safety-critical, or emergency applications.</p>

        <h2 style={S.h2}>7. Audio data</h2>
        <p style={S.p}>By uploading audio you grant us the right to process it for the purpose of providing the service (transcription, diagnostics, TTS synthesis). We do not claim ownership of your audio. We do not share it with third parties.</p>

        <h2 style={S.h2}>8. Disclaimer of warranties</h2>
        <p style={S.p}>THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

        <h2 style={S.h2}>9. Limitation of liability</h2>
        <p style={S.p}>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.</p>

        <h2 style={S.h2}>10. Termination</h2>
        <p style={S.p}>We reserve the right to suspend or terminate access to the service at any time, for any reason, without notice.</p>

        <h2 style={S.h2}>11. Changes to terms</h2>
        <p style={S.p}>We may modify these terms at any time. Continued use after changes constitutes acceptance. The effective date at the top will be updated.</p>

        <h2 style={S.h2}>12. Governing law</h2>
        <p style={S.p}>These terms are governed by the laws of the jurisdiction in which the service operator is located, without regard to conflict of law principles.</p>

      </div>
    </div>
  )
}
